export interface Participant {
  id: number;
  detectedName: string;
  avatarEmoji: string;
  emotion: string;
  apparelDescription: string;
  clothingColor: string; // Hex or nice CSS class
  hasGlasses: boolean;
  score: number;
  photoIndex?: number; // 0-indexed index of photos sent to Gemini
  faceBox?: [number, number, number, number]; // [ymin, xmin, ymax, xmax] in range [0, 1000]
  croppedFaceUrl?: string; // Generated on the frontend
  cartoonSvg?: string; // Generated by Gemini Asset Agent on the server
}

export interface SpawnItem {
  name: string;
  emoji: string;
  type: "collectable" | "hazard" | "powerup";
  points: number;
  description: string;
}

export interface CustomGameConfig {
  gameTitle: string;
  subtitle: string;
  dialogueIntro: string;
  gameTemplate: string;
  backdropType: "neon" | "sunset" | "cozy" | "retro" | "cyberpunk" | "nature";
  backdropSvg?: string; // High-detail premium landscape vector context SVG
  primaryColor: string;
  secondaryColor: string;
  gameSpeed: number;
  targetScore: number;
  spawnItems: SpawnItem[];
  vibeSummary: string;
  locationContextName: string;
}

export interface VibeAnalysisResult {
  vibeTitle: string;
  vibeDescription: string;
  groupThemeColors: string[];
  participants: Participant[];
  detectedActivity: string;
  funFact: string;
  gameConfig: CustomGameConfig;
}

export interface CapturedImage {
  id: string;
  base64: string;
  timestamp: string;
  label?: string;
}
